// Builds the Web Store / AMO upload zip (TESTING-TODO §7.1).
//
// Selection is a denylist — a new module must ship without anyone remembering to
// add it here, and forgetting a file breaks the extension at runtime, silently.
// The safety net for that trade-off is verify(): after staging, every file the
// manifest, the HTML pages and the ES imports actually reference must be present
// in the staged tree, or the build fails. So an over-eager exclusion cannot ship.
//
//   node tools/build-zip.mjs            → dist/yt-transcript-summarizer-<ver>.zip
//   node tools/build-zip.mjs --dry-run  → list what would ship, build nothing
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const DRY = process.argv.includes('--dry-run');

// Never ships. Each entry needs a reason.
const EXCLUDE_DIRS = new Set([
  'test',       // the suites and the E2E drivers (§7.1)
  'tools',      // this script
  'dist',       // previous builds
  '_metadata',  // generated by Chrome when the folder is loaded unpacked; a
                // stale generated_indexed_rulesets is rejected on upload
  '.git', 'node_modules', '.claude',
]);
const EXCLUDE_FILES = new Set([
  'NOTES.md',         // internal rationale notes (ex TESTING-TODO.md)
  'ROADMAP.md',       // public on GitHub, which is where a roadmap is read —
                      // inside the uploaded package it is dead weight, and it
                      // describes what the extension does NOT do yet, which is
                      // not what a store reviewer should be reading.
  'package.json', 'package-lock.json',
  // Unreferenced by the manifest and by every page — 400 KB of dead weight in
  // every upload. The store listing icon is uploaded separately, not from here.
  'icon.png',
]);
const EXCLUDE_EXT = new Set(['.zip', '.log', '.bak']);

function collect(dir = ROOT, rel = '') {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const relPath = rel ? `${rel}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      out.push(...collect(path.join(dir, entry.name), relPath));
    } else {
      if (EXCLUDE_FILES.has(entry.name) || entry.name.startsWith('.')) continue;
      if (EXCLUDE_EXT.has(path.extname(entry.name))) continue;
      out.push(relPath);
    }
  }
  return out;
}

/** Every local file path the shipped code points at, from all three sources. */
function referencedFiles(files) {
  const refs = new Set();
  const add = (from, p) => {
    if (!p || /^(https?:|data:|chrome:|#|\/\/)/.test(p)) return;
    const clean = p.split(/[?#]/)[0];
    if (!clean) return;
    // Resolve relative to the referring file, then back to a repo-relative path.
    const abs = path.resolve(path.dirname(path.join(ROOT, from)), clean);
    refs.add(path.relative(ROOT, abs).split(path.sep).join('/'));
  };

  const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'manifest.json'), 'utf8'));
  add('manifest.json', manifest.background?.service_worker);
  for (const s of manifest.background?.scripts ?? []) add('manifest.json', s);
  for (const cs of manifest.content_scripts ?? []) for (const j of cs.js ?? []) add('manifest.json', j);
  for (const i of Object.values(manifest.icons ?? {})) add('manifest.json', i);
  add('manifest.json', manifest.action?.default_popup);
  add('manifest.json', manifest.action?.default_icon);
  for (const r of manifest.declarative_net_request?.rule_resources ?? []) add('manifest.json', r.path);
  for (const w of manifest.web_accessible_resources ?? []) for (const p of w.resources ?? []) add('manifest.json', p);

  for (const f of files) {
    const ext = path.extname(f);
    if (ext !== '.html' && ext !== '.js' && ext !== '.css') continue;
    const src = fs.readFileSync(path.join(ROOT, f), 'utf8');
    if (ext === '.html') {
      for (const m of src.matchAll(/(?:src|href)\s*=\s*["']([^"']+)["']/g)) add(f, m[1]);
    } else if (ext === '.js') {
      // Static imports and re-exports only; a dynamic import() of a computed
      // path is not resolvable here and is not used in this codebase.
      for (const m of src.matchAll(/(?:^|\n)\s*(?:import|export)[^'"\n]*from\s*["']([^"']+)["']/g)) add(f, m[1]);
      for (const m of src.matchAll(/getURL\(\s*["']([^"']+)["']\s*\)/g)) add(f, m[1]);
    } else {
      for (const m of src.matchAll(/url\(\s*["']?([^"')]+)["']?\s*\)/g)) add(f, m[1]);
    }
  }
  return refs;
}

function verify(files) {
  const have = new Set(files);
  const missing = [...referencedFiles(files)].filter(r => !have.has(r));
  if (missing.length) {
    console.error('\n❌ These files are referenced by the shipped code but are NOT in the zip:');
    for (const m of missing) console.error(`   ${m}`);
    console.error('\nEither the exclusion lists in tools/build-zip.mjs are too broad, or the reference is dead.');
    process.exit(1);
  }
  console.log(`✅ all ${have.size} staged files consistent — every referenced path is present`);
}

const files = collect().sort();
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'manifest.json'), 'utf8'));
const total = files.reduce((n, f) => n + fs.statSync(path.join(ROOT, f)).size, 0);

console.log(`Version ${manifest.version} — ${files.length} files, ${(total / 1024).toFixed(0)} KB uncompressed\n`);
for (const f of files) console.log(`  ${f}`);
console.log();
verify(files);

if (DRY) { console.log('\n--dry-run: nothing written'); process.exit(0); }

const zip = path.join(ROOT, 'dist', `yt-transcript-summarizer-${manifest.version}.zip`);
fs.mkdirSync(path.dirname(zip), { recursive: true });
fs.writeFileSync(zip, buildZip(files));

console.log(`\n📦 ${path.relative(ROOT, zip)} — ${(fs.statSync(zip).size / 1024).toFixed(0)} KB`);

// ── Minimal ZIP writer ───────────────────────────────────────────────────────
// Written by hand rather than shelled out to Compress-Archive, which on Windows
// PowerShell 5.1 stores entry names with BACKSLASH separators. The format
// requires '/', and a store validator reading `modules\config.js` sees one
// oddly-named file at the root instead of a module — the extension then fails
// review, or installs and cannot resolve its own imports.
function crc32(buf) {
  let c = ~0;
  for (let i = 0; i < buf.length; i++) {
    c ^= buf[i];
    for (let k = 0; k < 8; k++) c = (c >>> 1) ^ (0xEDB88320 & -(c & 1));
  }
  return ~c >>> 0;
}

function buildZip(entries) {
  const local = [];
  const central = [];
  let offset = 0;

  for (const name of entries) {
    const data = fs.readFileSync(path.join(ROOT, name));
    const deflated = zlib.deflateRawSync(data, { level: 9 });
    // Only store the compressed form when it actually helps (logo.png does not).
    const stored = deflated.length >= data.length;
    const body = stored ? data : deflated;
    const method = stored ? 0 : 8;
    const crc = crc32(data);
    // Entry names are POSIX by construction: `collect()` joins with '/'.
    const nameBuf = Buffer.from(name, 'utf8');
    // Bit 11 marks the name as UTF-8, the only encoding the spec defines besides
    // CP437 — without it a non-ASCII filename would be read as mojibake.
    const flags = 0x0800;

    const lh = Buffer.alloc(30);
    lh.writeUInt32LE(0x04034b50, 0); lh.writeUInt16LE(20, 4); lh.writeUInt16LE(flags, 6);
    lh.writeUInt16LE(method, 8);
    lh.writeUInt16LE(0, 10); lh.writeUInt16LE(0x21, 12);   // fixed DOS time/date:
    // a constant timestamp makes the build reproducible — the same sources
    // always produce a byte-identical zip.
    lh.writeUInt32LE(crc, 14);
    lh.writeUInt32LE(body.length, 18); lh.writeUInt32LE(data.length, 22);
    lh.writeUInt16LE(nameBuf.length, 26); lh.writeUInt16LE(0, 28);
    local.push(lh, nameBuf, body);

    const ch = Buffer.alloc(46);
    ch.writeUInt32LE(0x02014b50, 0); ch.writeUInt16LE(20, 4); ch.writeUInt16LE(20, 6);
    ch.writeUInt16LE(flags, 8); ch.writeUInt16LE(method, 10);
    ch.writeUInt16LE(0, 12); ch.writeUInt16LE(0x21, 14);
    ch.writeUInt32LE(crc, 16);
    ch.writeUInt32LE(body.length, 20); ch.writeUInt32LE(data.length, 24);
    ch.writeUInt16LE(nameBuf.length, 28);
    ch.writeUInt32LE(0o644 << 16, 38);                      // external attrs
    ch.writeUInt32LE(offset, 42);
    central.push(ch, nameBuf);

    offset += lh.length + nameBuf.length + body.length;
  }

  const centralBuf = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralBuf.length, 12); end.writeUInt32LE(offset, 16);
  return Buffer.concat([...local, centralBuf, end]);
}
